### ISSUE TITLE
Not sure how to get this to work

### ISSUE THREAD

**Issue by mclacore** [noperator/jqfmt#4]
I have a `.jq` file I'm trying to get this to work on, but struggling. It doesn't seem like it can read the contents of my file. I'm trying to cat the contents of a file into `jqfmt` and im just getting this error:
```
❯ cat artifact.jq | jqfmt
FATA[0000] could not format jq: could not read file: open /Users/myuser/.jq: no such file or directory
```
Any ideas? Is it possible to run it against a file and update the file?

**Comment by noperator** [comment]
[Removed](https://github.com/noperator/jqfmt/commit/5a3adae4e7592bf4f2ac10cc38ea26a0fba950b3) the `.jq`-related logic for now; it was related to some partially implemented functionality to process functions, modules, etc. Will reintroduce in the future once it's all working.
